Recipes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new_recipe", views.new_recipe, name="new_recipe"),

    # API routes
    path("add_recipe", views.add_recipe, name="add_recipe"),
    path("all_recipes", views.all_recipes, name="all_recipes"),
    path("recipe_page/<str:title>", views.get_recipe, name="recipe_page"),
    path("update_rating/<str:name>", views.update_rating, name="update_rating"),
    path("search_recipes/<str:title>", views.search_recipes, name="search_recipes"),
    path("my_recipes", views.my_recipes, name="my_recipes"),
    path("cuisines", views.cuisines, name="cuisines"),
    path("meals", views.meals, name="meals"),
    path("cuisine_recipes/<str:cuisine>", views.cuisine_recipes, name="cuisine_recipes"),
    path("meal_recipes/<str:meal>", views.meal_recipes, name="meal_recipes"),
    path("favorites", views.favorites, name="favorites"),
    path("update_favorites/<str:title>", views.update_favorites, name="update_favorites"),
    path("add_comment/<str:title>", views.add_comment, name="add_comment"),
    path("remove_comment/<int:id>", views.remove_comment, name="remove_comment"),
    path("delete_recipe/<str:title>", views.delete_recipe, name="delete_recipe"),
    path("update_recipe/<str:title>", views.update_recipe, name="update_recipe"),
    path("autocomplete/", views.autocomplete, name="autocomplete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import subprocess
import os

from django.contrib.auth.models import AbstractUser
from django.db import models
from PIL import Image
from django.utils import timezone
import re
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .custom_storage import OverwriteStorage
from django.core.files import File
from io import BytesIO


class User(AbstractUser):
    """
    Represents a user of the recipes book.
    Adds a "favorites" relationship between a user and a recipe to the built-in Django user model.
    """
    favorites = models.ManyToManyField('Recipe', symmetrical=False, blank=True, related_name="favoriters")

    def serialize(self):
        return {
            "favorites": [recipe.title for recipe in self.favorites.all()],
        }


class Recipe(models.Model):
    """
    Represents a recipe entry into the app"
    """
    user = models.ForeignKey("User", on_delete=models.CASCADE, null=True, related_name="recipes")
    title = models.CharField(max_length=50, null=True)
    ingredients = models.CharField(max_length=5000, null=True, blank=True)
    instructions = models.CharField(max_length=50000, null=True, blank=True)
    category = models.CharField(max_length=50, null=True)
    meal = models.CharField(max_length=50, null=True)
    image = models.ImageField(upload_to='images/', storage=OverwriteStorage(), blank=True)
    cooktime = models.CharField(max_length=50, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    note = models.CharField(max_length=500, blank=True)
    user_rating = models.CharField(max_length=50000, null=True, blank=True)


    # def save(self, *args, **kwargs):
    #     """
    #     Override image save method to crop photo to square for display.
    #     """
    #     if self.image:
    #         print(f"Image name: {self.image.name}")
    #         print(f"Image URL: {self.image.url}")
    #         print(f"Image path: {self.image.path}")

    #         AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    #         AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

    #         if "images/images" in self.image.name:
    #             self.image.name = os.path.basename(self.image.name)
    #             print(f"Corrected name: {self.image.name}")
    #             self.image.path = f'/media/images/{self.image.name}'
    #             print(f"Corrected URL: {self.image.url}")
    #             self.image.url = f'https://{AWS_S3_CUSTOM_DOMAIN}/images/{self.image.name}'
    #             print(f"Corrected path: {self.image.path}")

    #         self.image.file.seek(0)  # Reset file pointer
    #         img = Image.open(self.image.file)

    #         print("Image opened")
    #         img = img.convert('RGB')
    #         print("Image rgb")
    #         width, height = img.size
    #         min_side = min(width, height)
    #         left = (width - min_side) / 2
    #         top = (height - min_side) / 2
    #         right = (width + min_side) / 2
    #         bottom = (height + min_side) / 2
    #         img = img.crop((left, top, right, bottom))
    #         print("Image cropped")
    #         img_io = BytesIO()
    #         img.save(img_io, format='JPEG')
    #         print("Image io saved")

    #         self.image.save(self.image.name, img_io, save=False)

    #     print("Super Save")
    #     super().save(*args, **kwargs)  # Call the "real" save() method to save the image field


    def save(self, *args, **kwargs):

        img_flag = kwargs.pop('flag', True)
        
        # Construct the AWS CLI command
        if img_flag:
            bucket_name = os.getenv('BUCKETEER_BUCKET_NAME')
            object_name = f'media/images/{self.image.name}'
            save_path = os.path.join(settings.MEDIA_ROOT, 'images')
            fs = FileSystemStorage(location=save_path)

            if self.image.file.readable():
                fs.save(self.image.name, self.image.file)

            else:
                # Fallback logic: Use static image in the source code
                static_file_path = os.path.join(
                    settings.BASE_DIR, 'static', 'images', 'no_image.jpeg'
                )

                try:
                    # Open the static file and wrap it in a Django File object
                    with open(static_file_path, 'rb') as f:
                        file_content = BytesIO(f.read())  # Read content and wrap in BytesIO
                        fallback_image = File(file_content, name='no_image.jpeg')

                        # Assign the fallback image to the ImageField
                        self.image.save(fallback_image.name, fallback_image, save=False)
                except FileNotFoundError:
                    print("Not saved!")
                    raise ValueError("Fallback image not found in static/images!")
                
            file_url = save_path + "/" + self.image.name

            command = [
                'aws', 's3', 'cp', file_url,
                f's3://{bucket_name}/{object_name}'
            ]

            try:
                # Run the command using subprocess
                result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                print("Upload successful:", result.stdout.decode('utf-8'))
            except subprocess.CalledProcessError as e:
                print("Upload failed:", e.stderr.decode('utf-8'))
        else:
            print("No new image uploaded, using original image.")

        super().save(*args, **kwargs)

    
    def delete(self, *args, **kwargs):

        if self.image.name != "images/no_image.jpeg":
            bucket_name = os.getenv('BUCKETEER_BUCKET_NAME')
            object_name = f'media/{self.image.name}'

            command = [
                'aws', 's3', 'rm',
                f's3://{bucket_name}/{object_name}'
            ]

            try:
                # Run the command using subprocess
                result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                print("Delete successful:", result.stdout.decode('utf-8'))
            except subprocess.CalledProcessError as e:
                print("Delete failed:", e.stderr.decode('utf-8'))

        super().delete(*args, **kwargs)


    def user_rating_dict(self):
        """
        Make a dict object from user rating charfield.
        """
        rating_dict = dict()
        if self.user_rating is not None:

            # get rid of {} and split by dict entry
            rating_str = self.user_rating[1:-1]
            ratings_list = rating_str.split(",")

            # loop through each entry and split into separate key: value pairs
            for entry in ratings_list:
                current_entry = entry.split(":")

                # trim off extra characters from converting between string and dictionary types
                username = current_entry[0].strip()
                rating = current_entry[1].strip()
                start_ind, end_ind = 0, len(username) - 1
                if re.search(r"[a-zA-Z0-9_]", username) is not None:
                    res1 = re.search(r"[a-zA-Z0-9_]", username)
                    res2 = re.search(r"[a-zA-Z0-9_]", username[::-1])
                    start_ind, end_ind = res1.start(), res2.start()
                rating_dict[username[start_ind:len(username) - end_ind]] = int(rating)

        return rating_dict

    def num_ratings(self):
        """
        Get the number of ratings for a given recipes.
        """
        if self.user_rating_dict():
            return len(self.user_rating_dict().values())
        else:
            return 0

    def avg_rating(self):
        """
        Get the average value of the user ratings for display.
        """
        if self.user_rating_dict():
            return round(sum(self.user_rating_dict().values())/self.num_ratings(), 1)
        else:
            return 0

    def stringify_comments(self):
        """
        Get all the comments for a specified recipe.
        """
        if self.recipe_comments.all():
            return [comment.serialize() for comment in self.recipe_comments.order_by("-timestamp").all()]
        else:
            return None

    def serialize(self):
        local_timestamp = timezone.localtime(self.timestamp)
        return {
            "id": self.id,
            "title": self.title,
            "poster": self.user.username,
            "ingredients": self.ingredients,
            "instructions": self.instructions,
            "category": self.category,
            "meal": self.meal,
            "image": self.image.url,
            "cooktime": self.cooktime,
            "timestamp": local_timestamp.strftime("%b %d %Y, %I:%M %p"),
            "note": self.note,
            "rating": self.avg_rating(),
            "num_ratings": self.num_ratings(),
            "comments": self.stringify_comments()
        }


class Comment(models.Model):
    """
    Represents a user comment on a recipe.
    """
    text = models.CharField(max_length=250, null=True)
    user = models.ForeignKey("User", on_delete=models.CASCADE, null=True, related_name="user_comments")
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, null=True, related_name="recipe_comments")
    timestamp = models.DateTimeField(auto_now_add=True)

    def serialize(self):
        return {
            "id": self.id,
            "comment": self.text,
            "poster": self.user.username,
            "timestamp": self.timestamp.strftime("%b %d %Y, %I:%M %p")
        }

app/templates/app/index.html
{% extends "app/layout.html" %}
{% load static %}

{% block body %}
    <div id="spinner" style="display: none;"></div>
    <div id="all_recipes-view">
        <div id="page-banner">
            <h3 id="recipes-title"></h3>
            <img src="https://static.thenounproject.com/png/568541-200.png" class="help-icon" id="search-help">
            <p class="help-box" id="help-box2">Search for recipes by title (case insensitive) or by ingredients using ',' seperated list.  Ex) "Apple, Banana" or just "ap"</p>
            <a id="new_recipe-link" href="new_recipe">Add New Recipe</a>
            <hr>
        </div>
        <div id="all_recipes"></div>
        <div id="cuisines-view">
            <ul id="cuisines" class="matched_recipe-list"></ul>
        </div>
        <div id="meals-view">
            <ul id="meals" class="matched_recipe-list"></ul>
        </div>
        <div id="favorites-view"></div>
        <div id="recipe-view">
            <div id="recipe-image-div"></div>
            <div id="top-recipe-info"></div>
            <div id="recipe-info-lists"></div>
            <div id="favorites-div">
                <button id="favorites-button" class="btn btn-sm btn-outline-primary"></button>
            </div>
        </div>

        <div id="matched_recipes-view">
            <h4>Recipes with key word(s): <span id="header" class="search_header"></span></h4>
            <div id="d1" class="list_div">
                <ul id="ul1" class="rec"></ul>
            </div>
            <div id="d2" class="list_div">
                <ul id="ul2" class="rec"></ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js" defer></script>
    <script src="{% static 'recipes.js' %}" defer></script>
{% endblock %}

app/templates/app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}House Recipes{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% block script %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
            {% load static %}
            <img src="{% static 'images/logo.png' %}" id="logo">
            <div>
                <ul class="navbar-nav mr-auto=" id="nav_bar">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <p class="nav-link" id="usrname"><strong id="name">{{ user.username }}</strong></p>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" id="allRecipes-link" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link" id="Favoirtes-link">Favorites</p>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link" id="Cuisines-link">Cuisines</p>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link" id="Meals-link">Meals</p>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Register</a>
                        </li>
                    {% endif %}
                    <li id="search_bar">
                        <input style="width: 260px; border: none; background-color: transparent; border-radius: 15px;
                        padding-left: 10px;" id="search_box" type="text" placeholder=" Search recipes...">
                        <button class="search-button" id="search-button">
                            {% load static %}
                            <img src="{% static 'images/search.jpeg' %}">
                        </button>
                    </li>
                </ul>
            </div>
        </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block body %}
    <div class="login-container">
        <h2>Login</h2>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Login">
        </form>

        Don't have an account? <a href="{% url 'register' %}">Register here.</a>
    </div>

{% endblock %}

app/templates/app/new_recipe.html
{% extends "app/layout.html" %}
{% load static %}

{% block body %}

    <div id="title-div">
        <h2 id="new-recipe-title">Add New Recipe</h2>
        <img src="https://static.thenounproject.com/png/568541-200.png" class="help-icon" id="new-recipe-help">
        <p class="help-box" id="help-box1">
            <span>Ingredients, Cooking Instructions, and Additional Notes can be added in list format using ';' as the delimiter.  Ex) Note1; Note2; Notes3.</span><br>
            <span>Numbering and bulleting the list will be handled automatically.</span>
        </p>
    </div>

    <div class="outer">
        <p class="error-message"></p>
        <form method="post" id="new_recipe-form">
            {% csrf_token %}
            <div class="new_recipe-entry">
                <p class="container">
                    <span class="label">Title: </span>
                    <span class="new_recipe-info" id="title_entry">
                        <input type="text" name="title" maxlength="50" required id="id_title" class="input_width">
                    </span>
                </p>
                <p class="container">
                    <span class="label">Ingredients: </span>
                    <textarea class="new_recipe-info" id="ingredients_entry" required name="ingredients"></textarea>
                </p>
                <p id="cooking_container" class="container">
                    <span id="instructions_label" class="label">Cooking Instructions: </span>
                    <textarea class="new_recipe-info" id="instructions_entry" name="instructions"></textarea>
                </p>
                <p class="container">
                    <span class="label">Cuisine: </span>
                    <span class="new_recipe-info" id="category_entry">
                        <input type="text" name="category" maxlength="50" required id="id_category" class="input_width" autocomplete="off">
                        <div id="suggestions-id_category" class="suggestions"></div>
                    </span>
                </p>
                <p class="container">
                    <span class="label">Meal: </span>
                    <span class="new_recipe-info" id="meal_entry">
                        <input type="text" name="meal" maxlength="50" required id="id_meal" class="input_width">
                        <div id="suggestions-id_meal" class="suggestions"></div>
                    </span>
                </p>
                <p class="container">
                    <span class="label">Add Image: </span>
                    <span class="new_recipe-info" id="image_entry">
                        <input type="file" name="image" accept="image/*" id="id_image" class="input_width">
                    </span>
                </p>
                <p class="container">
                    <span class="label">Cooktime: </span>
                    <span class="new_recipe-info" id="cooktime_entry">
                        <input type="text" name="cooktime" maxlength="50" required id="id_cooktime" class="input_width">
                    </span>
                </p>
                <p class="container">
                    <span class="label">Additional Notes: </span>
                    <textarea class="new_recipe-info" id="note_entry"></textarea>
                </p>
                <button class="btn btn-primary" id="new_recipe-button" type="submit">Add Recipe</button>
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'create_recipe.js' %}"></script>
{% endblock %}

app/templates/app/register.html
{% extends "app/layout.html" %}

{% block body %}
    <div class="login-container">
        <h2>Register</h2>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Register">
        </form>

        Already have an account? <a href="{% url 'login' %}">Log In here.</a>
    </div>

{% endblock %}